test:
  max_actions: 20
  daily_actions: 6
  starting_actions: 6
  stranger_actions: 2
development:
  max_actions: 20
  daily_actions: 6
  starting_actions: 6
  stranger_actions: 2
production:
  max_actions: 20
  daily_actions: 6
  starting_actions: 6
  stranger_actions: 2